version: 2

models:
  - name: date_dim
    description: "Date dimension for use in all time-based analysis"
    columns:
      - name: date
        description: "Primary key"
        tests: [unique, not_null]

  - name: transformed_personal_parkrun
    description: "Fact table for personal parkrun results"
    columns:
      - name: "Run Date"
        description: "Event date"
      - name: vTotalSeconds
        description: "Total finish time in seconds"
      - name: decimal_age_grade
        description: "Normalized performance"

  - name: event_dim
    description: "Dimension table of parkrun events"
    columns:
      - name: event_sk
        description: "Surrogate key for event"
        tests:
          - not_null
          - unique
